//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MockDataGenerator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MockDataGenerator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap alt_parameters_icone_9469_64 {
            get {
                object obj = ResourceManager.GetObject("alt_parameters_icone_9469_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Associate2 {
            get {
                object obj = ResourceManager.GetObject("Associate2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap atom__elementary_particle_pic {
            get {
                object obj = ResourceManager.GetObject("atom__elementary_particle_pic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap automator_icon {
            get {
                object obj = ResourceManager.GetObject("automator_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Back_arrow_icon {
            get {
                object obj = ResourceManager.GetObject("Back_arrow_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Banner {
            get {
                object obj = ResourceManager.GetObject("Banner", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap binoculars {
            get {
                object obj = ResourceManager.GetObject("binoculars", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap colorfuldragon3pm2 {
            get {
                object obj = ResourceManager.GetObject("colorfuldragon3pm2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novartis
        ///Nestle
        ///Roche
        ///Anheuser-Busch InBev
        ///Royal Dutch Shell
        ///HSBC
        ///Sanofi
        ///Volkswagen
        ///Bayer
        ///Unilever
        ///Total
        ///BP
        ///Novo Nordisk
        ///GlaxoSmithKline
        ///Banco Santander
        ///Daimler
        ///L&apos;Oreal
        ///Inditex
        ///British American Tobacco
        ///Basf
        ///Siemens
        ///LVMH
        ///SAP
        ///AstraZeneca
        ///Vodafone Group
        ///SabMiller
        ///Deutsche Telekom
        ///Lloyds Banking Group
        ///BMW
        ///Allianz
        ///BNP Paribas
        ///UBS
        ///Telefonica
        ///Diageo
        ///BBVA
        ///Prudential
        ///Eni
        ///Reckitt Benckiser
        ///Axa
        ///Barclays
        ///Hennes &amp; Mauritz
        ///Rio Tinto
        ///Intesa Sanpaolo
        ///Gazprom
        ///ING
        ///Statoil
        ///Glencor [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string European_Companies {
            get {
                return ResourceManager.GetString("European_Companies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MARY           
        ///PATRICIA       
        ///LINDA          
        ///BARBARA        
        ///ELIZABETH      
        ///JENNIFER       
        ///MARIA          
        ///SUSAN          
        ///MARGARET       
        ///DOROTHY        
        ///LISA           
        ///NANCY          
        ///KAREN          
        ///BETTY          
        ///HELEN          
        ///SANDRA         
        ///DONNA          
        ///CAROL          
        ///RUTH           
        ///SHARON         
        ///MICHELLE       
        ///LAURA          
        ///SARAH          
        ///KIMBERLY       
        ///DEBORAH        
        ///JESSICA        
        ///SHIRLEY        
        ///CYNTHIA        
        ///ANGELA         
        ///MELISSA        
        ///BR [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Female_Names {
            get {
                return ResourceManager.GetString("Female_Names", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ForeWard {
            get {
                object obj = ResourceManager.GetObject("ForeWard", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap help {
            get {
                object obj = ResourceManager.GetObject("help", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Icon {
            get {
                object obj = ResourceManager.GetObject("Icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ##Basic Materials
        ///Agricultural Chemicals
        ///Aluminum
        ///Chemicals - Major Diversified
        ///Copper
        ///Gold
        ///Independent Oil &amp; Gas
        ///Industrial Metals &amp; Minerals
        ///Major Integrated Oil &amp; Gas
        ///Nonmetallic Mineral Mining
        ///Oil &amp; Gas Drilling &amp; Exploration
        ///Oil &amp; Gas Equipment &amp; Services
        ///Oil &amp; Gas Pipelines
        ///Oil &amp; Gas Refining &amp; Marketing
        ///Silver
        ///Specialty Chemicals
        ///Steel &amp; Iron
        ///Synthetics
        ///##Conglomerates
        ///Conglomerates
        ///##Consumer Goods
        ///Appliances
        ///Auto Manufacturers - Major
        ///Auto Parts
        ///Beverages - Brewers
        ///Beverage [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Industry_Sectors {
            get {
                return ResourceManager.GetString("Industry_Sectors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMITH          
        ///JOHNSON        
        ///WILLIAMS       
        ///JONES          
        ///BROWN          
        ///DAVIS          
        ///MILLER         
        ///WILSON         
        ///MOORE          
        ///TAYLOR         
        ///ANDERSON       
        ///THOMAS         
        ///JACKSON        
        ///WHITE          
        ///HARRIS         
        ///MARTIN         
        ///THOMPSON       
        ///GARCIA         
        ///MARTINEZ       
        ///ROBINSON       
        ///CLARK          
        ///RODRIGUEZ      
        ///LEWIS          
        ///LEE            
        ///WALKER         
        ///HALL           
        ///ALLEN          
        ///YOUNG          
        ///HERNANDEZ      
        ///KING           
        ///WR [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LastNames {
            get {
                return ResourceManager.GetString("LastNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afghanistan
        ///Albania
        ///Algeria
        ///Andorra
        ///Angola
        ///Antigua and Barbuda
        ///Argentina
        ///Armenia
        ///Aruba
        ///Australia
        ///Austria
        ///Azerbaijan
        ///Bahamas, The
        ///Bahrain
        ///Bangladesh
        ///Barbados
        ///Belarus
        ///Belgium
        ///Belize
        ///Benin
        ///Bhutan
        ///Bolivia
        ///Bosnia and Herzegovina
        ///Botswana
        ///Brazil
        ///Brunei 
        ///Bulgaria
        ///Burkina Faso
        ///Burma
        ///Burundi
        ///Cambodia
        ///Cameroon
        ///Canada
        ///Cabo Verde
        ///Central African Republic
        ///Chad
        ///Chile
        ///China
        ///Colombia
        ///Comoros
        ///Congo, Democratic Republic of the
        ///Congo, Republic of the
        ///Costa Rica
        ///Cote d&apos;Ivoire
        ///Croatia [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string List_Of_Countires {
            get {
                return ResourceManager.GetString("List_Of_Countires", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abbey Mews
        ///Abbey Terrace
        ///Abbots Lane
        ///Abbot&apos;s Place
        ///Abbotswell Road
        ///Aberavon Road
        ///Abourne Street
        ///Adams Row
        ///Adderley Street
        ///Addison Place
        ///Adelaide Avenue
        ///Adelaide Close 
        ///Adelaide Grove
        ///Adelina Grove 
        ///Adeline Place
        ///Adenmore Road
        ///Admiral Street
        ///Agar Grove
        ///Ainsworth Road
        ///Alba Place
        ///Albemarle Way
        ///Albert Drive
        ///Albert Gardens
        ///Albert Terrace Mews
        ///Alberta Cottages
        ///Albion Avenue
        ///Albion Close
        ///Albion Mews
        ///Albion Way
        ///Albyn Road 
        ///Alders Court
        ///Aldersgate Street 
        ///Aldred Street
        ///Alexandra Driv [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string List_Of_Streets {
            get {
                return ResourceManager.GetString("List_Of_Streets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alabama,	AL	
        ///Alaska,	AK	
        ///Arizona,	AZ	
        ///Arkansas,	AR	
        ///California,	CA	
        ///Colorado,	CO	
        ///Connecticut,	CT	
        ///Delaware,	DE	
        ///Florida,	FL	
        ///Georgia,	GA	
        ///Hawaii,	HI	
        ///Idaho,	ID	
        ///Illinois, IL	
        ///Indiana,	IN	
        ///Iowa,	IA	
        ///Kansas,	KS	
        ///Kentucky,	KY	
        ///Louisiana,	LA	
        ///Maine,	ME	
        ///Maryland,	MD	
        ///Massachusetts,	MA	
        ///Michigan,	MI	
        ///Minnesota,	MN	
        ///Mississippi,	MS	
        ///Missouri,	MO	
        ///Montana,	MT
        ///Nebraska,	NE
        ///Nevada,	NV
        ///New Hampshire,	NH
        ///New Jersey,	NJ
        ///New Mexico,	NM
        ///New York,	NY
        ///North Carolina,	NC
        ///North Dakota,	ND
        ///O [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string List_Of_US_States {
            get {
                return ResourceManager.GetString("List_Of_US_States", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JAMES          
        ///JOHN           
        ///ROBERT         
        ///MICHAEL        
        ///WILLIAM        
        ///DAVID          
        ///RICHARD        
        ///CHARLES        
        ///JOSEPH         
        ///THOMAS         
        ///CHRISTOPHER    
        ///DANIEL         
        ///PAUL           
        ///MARK           
        ///DONALD         
        ///GEORGE         
        ///KENNETH        
        ///STEVEN         
        ///EDWARD         
        ///BRIAN          
        ///RONALD         
        ///ANTHONY        
        ///KEVIN          
        ///JASON          
        ///MATTHEW        
        ///GARY           
        ///TIMOTHY        
        ///JOSE           
        ///LARRY          
        ///JEFFREY        
        ///FR [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Male_Names {
            get {
                return ResourceManager.GetString("Male_Names", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mini_open_folder_full {
            get {
                object obj = ResourceManager.GetObject("mini_open_folder_full", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap miniPreview {
            get {
                object obj = ResourceManager.GetObject("miniPreview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NetIcon_web_design_edinburgh_hosting_png_300x263 {
            get {
                object obj = ResourceManager.GetObject("NetIcon_web_design_edinburgh_hosting_png_300x263", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap network {
            get {
                object obj = ResourceManager.GetObject("network", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NewProject {
            get {
                object obj = ResourceManager.GetObject("NewProject", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to actor, puppeteer/marionetteer (actor/actress)
        ///	
        ///actuary
        ///	
        ///administrative worker
        ///	
        ///advertising manager
        ///	
        ///aerial rigger
        ///	
        ///agricultural adviser (farming adviser)
        ///	
        ///agricultural machinery mechanic (agricultural mechanic)
        ///	
        ///agronomist
        ///	
        ///air traffic controller
        ///	
        ///air traffic safety technician
        ///	
        ///aircraft instrument technician
        ///	
        ///aircraft mechanic
        ///	
        ///airline clerk (airline ticket agent)
        ///	
        ///ammunition and explosives operative (munitions worker)
        ///	
        ///animal technician
        ///	
        ///animator
        ///	
        ///anthropolog [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Occupations {
            get {
                return ResourceManager.GetString("Occupations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Open {
            get {
                object obj = ResourceManager.GetObject("Open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap QA {
            get {
                object obj = ResourceManager.GetObject("QA", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap save_as2 {
            get {
                object obj = ResourceManager.GetObject("save_as2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Save2 {
            get {
                object obj = ResourceManager.GetObject("Save2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Universal_Database_Reduced {
            get {
                object obj = ResourceManager.GetObject("Universal_Database_Reduced", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Universal_DatabaseMedium {
            get {
                object obj = ResourceManager.GetObject("Universal_DatabaseMedium", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap update {
            get {
                object obj = ResourceManager.GetObject("update", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sitka,	Alaska
        ///Juneau,	Alaska
        ///Wrangell,	Alaska
        ///Anchorage,	Alaska
        ///Jacksonville,	Florida
        ///Anaconda,	Montana
        ///Butte,	Montana
        ///Oklahoma City,	Oklahoma
        ///Houston,	Texas
        ///Phoenix,	Arizona
        ///Nashville,	Tennessee
        ///Los Angeles,	California
        ///San Antonio,	Texas
        ///Suffolk,	Virginia
        ///Buckeye,	Arizona
        ///Indianapolis,	Indiana
        ///Chesapeake,	Virginia
        ///Dallas,	Texas
        ///Fort Worth,	Texas
        ///Louisville,	Kentucky
        ///San Diego,	California
        ///Memphis,	Tennessee
        ///Kansas City,	Missouri
        ///New York City,	New York
        ///Augusta,	Georgia
        ///Austin,	Texas [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string US_Cities {
            get {
                return ResourceManager.GetString("US_Cities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apple
        ///Exxon Mobil
        ///Berkshire Hathaway
        ///Google
        ///Microsoft
        ///Wells Fargo
        ///Johnson &amp; Johnson
        ///Wal-Mart Stores
        ///General Electric
        ///JP Morgan Chase
        ///Procter &amp; Gamble
        ///Pfizer
        ///Verizon Communications
        ///Chevron
        ///Oracle
        ///Facebook
        ///Walt Disney
        ///Coca-Cola
        ///Amazon.com
        ///AT&amp;T
        ///Merck
        ///Bank of America
        ///IBM
        ///Citigroup
        ///Home Depot
        ///Intel
        ///Gilead Sciences
        ///Comcast
        ///PepsiCo
        ///Cisco Systems
        ///Visa
        ///Amgen
        ///Actavis
        ///CVS Caremark
        ///Philip Morris International
        ///Qualcomm
        ///UnitedHealth Group
        ///Medtronic
        ///Bristol Myers Squibb
        ///Schlumberger
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string US_Companies {
            get {
                return ResourceManager.GetString("US_Companies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code,Place Name,State,State Abbreviation,County,Latitude,Longitude,
        ///00210,Portsmouth,New Hampshire,NH,Rockingham,43.0059,-71.0132,
        ///00211,Portsmouth,New Hampshire,NH,Rockingham,43.0059,-71.0132,
        ///00212,Portsmouth,New Hampshire,NH,Rockingham,43.0059,-71.0132,
        ///00213,Portsmouth,New Hampshire,NH,Rockingham,43.0059,-71.0132,
        ///00214,Portsmouth,New Hampshire,NH,Rockingham,43.0059,-71.0132,
        ///00215,Portsmouth,New Hampshire,NH,Rockingham,43.0059,-71.0132,
        ///00401,Pleasantville,New York,NY,,41.1381,-73.7847,
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string US_PostalCodes {
            get {
                return ResourceManager.GetString("US_PostalCodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap viewer {
            get {
                object obj = ResourceManager.GetObject("viewer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
